### ISSUE TITLE
Internationalisation and guild-specific language selection

### ISSUE THREAD

**Issue by itsCryne** [fbrettnich/easypoll-bot#11]
### Is your feature request related to a problem? Please describe.

With almost **17k guilds** and **2.5 million users** EasyPoll is reaching a broad audience.
Many of those guilds and thus users are part of an international user base, whose mother tongue is not english.
As such, it can be inconvenient for them, that EasyPoll is only offered in english - and potential users could even decide against using EasyPoll.

### Describe the solution you'd like

A possible solution for this problem is to implement a guild-specific language option.
Discord already offers a way to [get the locale of users](https://discord.com/developers/docs/resources/user#user-object). For this to work, the `Identify` OAuth2 scope would be necessary, but this can be accomplished rather straightforward in the process of inviting the bot.
### Describe alternatives you've considered

Another option - which could also be used in combination with the first method - to offer a configurable per-guild language would be to add a command to EasyPoll which would enable the server team to change their preferred language.

### Additional context

I think it is now a really great time to add support for more languages as I'm sure, many talented people will help by contributing not only to the code which is needed for this change, but also to the translation of EasyPoll.

**Comment by fbrettnich** [comment]
Planned Command: `/setup language`

Change language via Discord Selection Menu (dropdown)
